name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build wheels
    needs: [ test, benchmark, code-quality, docs ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels and source distribution
        run: |
          python -m pip install build
          python -m build --wheel --sdist --outdir dist
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*

  upload-pypi:
    name: Upload to PyPi
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: dist/

  release:
    name: Release on GitHub
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
