name: Tests, Code Quality, Build

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group test --all-extras
      - name: Run test suite
        run: uv run pytest --cov=order_matching

  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --group test --all-extras
      - name: Run benchmark
        run: uv run ./benchmark.sh
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: pytest
          output-file-path: benchmark.json
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          alert-comment-cc-users: '@${GITHUB_ACTOR},@khrapovs'
          auto-push: false
          benchmark-data-dir-path: "docs/dev/bench"

  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --all-groups --all-extras
      - name: Run pre-commit
        run: uv run prek run -v --show-diff-on-failure --all-files

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --group doc
      - name: Build documentation
        run: uv run mkdocs build -s -c

  publish:
    name: Build and publish wheels
    needs: [ test, benchmark, code-quality, docs ]
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/order-matching/
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
